require("plugins")
require("core.options")
require("core.keys")
require("core.colorscheme")

require("plugins.comment")
require("plugins.lualine")
require("plugins.nvim-tree")
require("plugins.telescope")

require("plugins.nvim-cmp")
require("plugins.lsp.mason")
require("plugins.lsp.lspsaga")
require("plugins.lsp.lspconfig")
require("plugins.lsp.none-ls")

require("plugins.indent_blankline")
require("plugins.noice")
require("plugins.which-key")
require("plugins.autopairs")
require("plugins.treesitter")
require("plugins.gitsigns")
require("plugins.bufferline")
